name: Validate README Steps

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - '.github/workflows/validate-readme.yml'
      - 'scripts/validate_readme.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'README.md'
      - '.github/workflows/validate-readme.yml'
      - 'scripts/validate_readme.py'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install validator dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests

    - name: Make validator script executable
      run: chmod +x scripts/validate_readme.py

    - name: Validate README
      run: ./scripts/validate_readme.py
